version: "3.4"

services:
  mihomo_tp:
    container_name: mihomo_tp
    image: ghcr.io/silencebay/mihomo-tproxy:premium-latest
    # privileged: true
    logging:
      options:
        max-size: '10m'
        max-file: '3'
    restart: unless-stopped
    volumes:
      - ./mihomo_config:/mihomo_config
    environment:
      - TZ=Asia/Shanghai
      - EN_MODE=redir-host
      # - FAKE_IP_RANGE=198.18.0.1/16
      #- LOCALNETWORK=127.0.0.0/8,10.0.0.0/8,192.168.0.0/16,224.0.0.0/4,172.16.0.0/12
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    networks:
      dMACvLAN:
        ipv4_address: 192.168.5.254
    dns:
      - 114.114.114.114

networks:
  dMACvLan:
    external:
      name: dMACvLan
