#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# `su` changes some environment variables, including HOME, we don't need that as the `-d` option is used
# su abc -c "/app/mihomo.sh"
exec \
    s6-setuidgid abc \
        /app/mihomo.sh
