#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -euo pipefail

# Function to format log messages
log_formatter() {
  while IFS= read -r line; do
    printf "\033[33m[radvd]\033[0m %s\n" "$line"
  done
}

# Run the radvd.sh script and format the output
/app/radvd.sh 2>&1 | log_formatter
