interface eth0 { ## 定义有IPv6的那个接口的名称，也就是旁路LAN口的名称
    IgnoreIfMissing on;
    AdvSendAdvert on;
    # AdvLinkMTU 1492;
    AdvManagedFlag off;  # M flag
    AdvOtherConfigFlag off;  # O flag
    MaxRtrAdvInterval 600;
    AdvReachableTime 0;
    AdvDefaultPreference high; ########重要
    AdvCurHopLimit 0;  # 默认 64，已通过容器的 sysctl 选项来设置
    prefix ::/64 { ### SLAAC模式下获取的前缀都是/64
        AdvAutonomous on;
        AdvPreferredLifetime 14400;
        AdvValidLifetime 86400;
        AdvOnLink on;
    };
    clients { ### 在此枚举需要进行流量牵引的设备的Link local地址
        #DEVICE 1
        fe80::aabb:ccdd:eeff:gghh;
    };
};