#!/bin/bash

set -e

echo -e "=================================="
echo -e "This script runs after post push  "
echo -e "=================================="

export MIHOMO_VERSION=$(docker run --entrypoint "" --rm $IMAGE_NAME bash -c 'mihomo -v')
MIHOMO_VERSION=$(echo $MIHOMO_VERSION | awk '{print $2}')

echo "Environment variables:
    IMAGE_NAME=$IMAGE_NAME
    DOCKER_REPO=$DOCKER_REPO
    DOCKER_TAG=$DOCKER_TAG
    SOURCE_BRANCH=$SOURCE_BRANCH
    BRANCH=$BRANCH
    MIHOMO_VERSION=$MIHOMO_VERSION
"

[ -z ${BRANCH+x} ] || export BRANCH_TAG="-$BRANCH"
docker tag $IMAGE_NAME ${DOCKER_REPO}:${DOCKER_TAG}${BRANCH_TAG}
docker push ${DOCKER_REPO}:${DOCKER_TAG}${BRANCH_TAG}


if [ -n ${MIHOMO_VERSION+x} ]; then
    docker tag $IMAGE_NAME ${DOCKER_REPO}:${DOCKER_TAG}${BRANCH_TAG}-${MIHOMO_VERSION}
    docker push ${DOCKER_REPO}:${DOCKER_TAG}${BRANCH_TAG}-${MIHOMO_VERSION}
fi

echo "post_push hook terminated successfully."