tproxy-port: 7893
mixed-port: 10801

allow-lan: true
bind-address: "*"

find-process-mode: off

geodata-loader: standard
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

mode: rule

log-level: info

ipv6: true

external-controller: 0.0.0.0:80
external-ui: dashboard/current

global-client-fingerprint: chrome

routing-mark: 6666

hosts:

profile:
  store-selected: false
  store-fake-ip: true

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - 10.1.1.98 # mosdns container
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: false
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
    - "+.localdomain"

  nameserver:
    - 10.1.1.98 # mosdns container

proxies:
  - name: socks
    type: socks5
    server: server
    port: 443
    # username: username
    # password: password
    # tls: true
    # fingerprint: xxxx
    # skip-cert-verify: true
    # udp: true
    # ip-version: ipv6

  - name: Proxy
    type: select
    proxies:
      - socks5

  - name: Final
    type: select
    proxies:
      - Proxy
      - DIRECT
      - REJECT

rules:
  - GEOIP,telegram,Telegram,no-resolve
  - GEOSITE,geolocation-!cn,Proxy
  - GEOSITE,cn,Domestic
  - GEOSITE,private,DIRECT
  - GEOIP,CN,Domestic
  - GEOIP,private,DIRECT
  - GEOIP,LAN,DIRECT
  - MATCH,Final
